Merge tag 'v3.10.105' into lineage-15.1
ec55e7c Linux 3.10.105
63d7f33 metag: Only define atomic_dec_if_positive conditionally
16654a5 fbdev/efifb: Fix 16 color palette entry calculation
fa88cd7 dm: mark request_queue dead before destroying the DM device
7fbbad1 regulator: tps65910: Work around silicon erratum SWCZ010
bc90bff ASoC: omap-mcpdm: Fix irq resource handling
a28d835 mfd: 88pm80x: Double shifting bug in suspend/resume
940d117 mpi: Fix NULL ptr dereference in mpi_powm() [ver #3]
2c8c5e6 hwmon: (adt7411) set bit 3 in CFG1 register
ebee2e2 can: dev: fix deadlock reported after bus-off
3419dc5 mm,ksm: fix endless looping in allocating memory when ksm enable
46049e5 dm flakey: fix reads to be issued if drop_writes configured
04be31f tile: avoid using clocksource_cyc2ns with absolute cycle count
569d62a PCI: Handle read-only BARs on AMD CS553x devices
bdb29c7 ACPI / APEI: Fix incorrect return value of ghes_proc()
2ef7229 mei: bus: fix received data size check in NFC fixup
0b0d4fc staging: iio: ad5933: avoid uninitialized variable in error case
c670aae hv: do not lose pending heartbeat vmbus packets
b9eabdf KEYS: Fix short sprintf buffer in /proc/keys show function
a6e9faf uio: fix dmem_region_start computation
4499fcbd gpio: mpc8xxx: Correct irq handler function
dd22893 cx231xx: fix GPIOs for Pixelview SBTVD hybrid
9865f08 cx231xx: don't return error on success
e3ba79c mb86a20s: fix demod settings
e80cf27 mb86a20s: fix the locking logic
8996ef0 pstore/ram: Use memcpy_fromio() to save old buffer
0d29b98 pstore/ram: Use memcpy_toio instead of memcpy
90efe9d pstore/core: drop cmpxchg based updates
98af342 mmc: block: don't use CMD23 with very old MMC cards
0d9dddc mmc: mxs: Initialize the spinlock prior to using it
6d97f02 PM / sleep: fix device reference leak in test_suspend
26b5a4a mfd: core: Fix device reference leak in mfd_clone_cell
479ce88b ratelimit: fix bug in time interval by resetting right begin time
fe5080a rcu: Fix soft lockup for rcu_nocb_kthread
9db8b64 tools/vm/slabinfo: fix an unintentional printf
f98c2c4 lib/genalloc.c: start search from start of chunk
7a59aff drbd: Fix kernel_sendmsg() usage - potential NULL deref
5dd23e6 cfq: fix starvation of asynchronous writes
3d971ee Revert "ipc/sem.c: optimize sem_lock()"
9c559b0 kernel/fork: fix CLONE_CHILD_CLEARTID regression in nscd
0d75118 tracing: Move mutex to protect against resetting of seq data
a1f5e91 kaweth: fix firmware download
c9dade9 net: sky2: Fix shutdown crash
85801b7 ipv4: Set skb->protocol properly for local output
3cc6c6b mwifiex: printk() overflow with 32-byte SSIDs
98db944 cfg80211: limit scan results cache size
f862950 mac80211: discard multicast and 4-addr A-MSDUs
293573d mac80211: fix purging multicast PS buffer queue
3816ef4 ipv4: use new_gw for redirect neigh lookup
4d4c1fc neigh: check error pointer instead of NULL for ipv4_neigh_lookup()
5b97e5f sctp: assign assoc_id earlier in __sctp_connect
261def5 dccp: fix out of bound access in dccp_v4_err()
7507bf3 dccp: do not send reset to already closed sockets
985f277 net: mangle zero checksum in skb_checksum_help()
9385be2 net: clear sk_err_soft in sk_clone_lock()
0058a4c sctp: validate chunk len before actually using it
2b8ed05b net: sctp, forbid negative length
5e6212f packet: call fanout_release, while UNREGISTERING a netdev
2943dca ipmr, ip6mr: fix scheduling while atomic and a deadlock with ipmr_get_route
9864f15 net: avoid sk_forward_alloc overflows
a5b7982 net: fix sk_mem_reclaim_partial()
4c1307b can: bcm: fix warning in bcm_connect/proc_register
b53cc17 netfilter: fix namespace handling in nf_log_proc_dostring
3ca5f49 firewire: net: fix fragmented datagram_size off-by-one
1d4353b firewire: net: guard against rx buffer overflows
afe6ced net/mlx4_core: Allow resetting VF admin mac to zero
3a8930f pstore: Fix buffer overflow while write offset equal to buffer size
ec38771 brcmfmac: avoid potential stack overflow in brcmf_cfg80211_start_ap()
3e56d98 brcmsmac: Initialize power in brcms_c_stf_ss_algo_channel_get()
5e26453 brcmsmac: Free packet if dma_mapping_error() fails in dma_rxfill
824c223 svc: Avoid garbage replies when pc_func() returns rpc_drop_reply
8d83a53 iwlwifi: pcie: fix access to scratch buffer
d53b660 ipvs: count pre-established TCP states as active
5a0b77d net: disable fragment reassembly if high_thresh is set to zero
eec89a7 mISDN: Fixing missing validation in base_sock_bind()
54fbda5 mISDN: Support DR6 indication in mISDNipac driver
49c201c net: ratelimit warnings about dst entry refcount underflow or overflow
745db35 bonding: Fix bonding crash
56325d9 tcp: take care of truncations done by sk_filter()
d318f82 tcp: fix wrong checksum calculation on MTU probing
93522d3 tcp: fix overflow in __tcp_retransmit_skb()
1c50d3a tcp: properly scale window in tcp_v[46]_reqsk_send_ack()
1340312 tcp: fix use after free in tcp_xmit_retransmit_queue()
942878e net/irda: handle iriap_register_lsap() allocation failure
68836e4 ip6_tunnel: disable caching when the traffic class is inherited
b030cd1 ip6_tunnel: Clear IP6CB in ip6tunnel_xmit()
c3a924e ipv6: dccp: add missing bind_conflict to dccp_ipv6_mapped
bd38061 ipv6: dccp: fix out of bound access in dccp_v6_err()
14ba02f ipv6: correctly add local routes when lo goes up
1735aab ip6_gre: fix flowi6_proto value in ip6gre_xmit_other()
b64222a ipv6: fix rtnl locking in setsockopt for anycast and multicast
04355d6 ipv6: addrconf: fix dev refcont leak when DAD failed
835b474 ipv6: move DAD and addrconf_verify processing to workqueue
973d595 ipv6: split duplicate address detection and router solicitation timer
af80b97 ipv6: don't call fib6_run_gc() until routing is ready
349759b stddef.h: move offsetofend inside #ifndef/#endif guard, neaten
1ddb794 include/stddef.h: Move offsetofend() from vfio.h to a generic kernel header
6cc73a1 drivers/vfio: Rework offsetofend()
5812a9bc vt: clear selection before resizing
902fd8d tty: vt, fix bogus division in csi_J
3505940 tty: limit terminal size to 4M chars
67de5f0a tty: Prevent ldisc drivers from re-using stale tty fields
ac74acf perf: Tighten (and fix) the grouping condition
d636f64 perf symbols: Fixup symbol sizes before picking best ones
44e3b0c mtd: nand: davinci: Reinitialize the HW ECC engine in 4bit hwctl
1b47a57 mtd: pmcmsp-flash: Allocating too much in init_msp_flash()
bdd7043 mtd: blkdevs: fix potential deadlock + lockdep warnings
aa19a88 IB/cm: Mark stale CM id's whenever the mad agent was unregistered
52aac91 IB/uverbs: Fix leak of XRC target QPs
1aecb8e IB/mlx4: Fix create CQ error flow
95bc51b IB/mlx4: Fix incorrect MC join state bit-masking on SR-IOV
b81459c IB/ipoib: Don't allow MC joins during light MC flush
4f0992c IB/core: Fix use after free in send_leave function
27816fe IB/ipoib: Fix memory corruption in ipoib cm mode connect flow
c6983c1 EDAC: Increment correct counter in edac_inc_ue_error()
de3e623 timers: Use proper base migration in add_timer_on()
d489808 cdc-acm: fix wrong pipe type on rx interrupt xfers
995a387 thermal: hwmon: Properly report critical temperature in sysfs
4813b8b iio: accel: kxsd9: Fix scaling bug
0f9dcb7 iio: accel: kxsd9: Fix raw read return
53f6ff2 i2c: at91: fix write transfers by clearing pending interrupt first
3c5054e i2c: core: fix NULL pointer dereference under race condition
c05b6f0 em28xx-i2c: rt_mutex_trylock() returns zero on failure
24e4e00 i2c-eg20t: fix race between i2c init and interrupt enable
8e9a1e98 hwrng: omap - Only fail if pm_runtime_get_sync returns < 0
1ef0fbf hwrng: omap - Fix assumption that runtime_get_sync will always succeed
08cd2b5 hwrng: exynos - Disable runtime PM on probe failure
cee7df2 Input: ili210x - fix permissions on "calibrate" attribute
76494f7 Input: i8042 - set up shared ps2_cmd_mutex for AUX ports
6a0f359 Input: i8042 - break load dependency between atkbd/psmouse and i8042
c23e6ab qxl: check for kmap failures
e5b91ef drm/radeon: Ensure vblank interrupt is enabled on DPMS transition to on
d948873 drm: Reject page_flip for !DRIVER_MODESET
85f44a4 drm/radeon: fix radeon_move_blit on 32bit systems
e7f6e3c driver core: fix race between creating/querying glue dir and its cleanup
2348b48 driver core: Delete an unnecessary check before the function call "put_device"
cb1f02f hostfs: Freeing an ERR_PTR in hostfs_fill_sb_common()
ca39cc1 isofs: Do not return EACCES for unknown filesystems
b24eac86 fs/super.c: fix race between freeze_super() and thaw_super()
3c15d16 fs/seq_file: fix out-of-bounds read
6b2e648 NFSv4: Open state recovery must account for file permission changes
e9276478 NFS: Don't drop CB requests with invalid principals
d5ab1c1 NFSD: Using free_conn free connection
cc2098e NFSv4.x: Fix a refcount leak in nfs_callback_up_net
8a3a266 UBI: fastmap: scrub PEB when bitflips are detected in a free PEB EC header
5558685 ubifs: Fix regression in ubifs_readdir()
1bf1f0c ubifs: Abort readdir upon error
d414505 UBIFS: Fix possible memory leak in ubifs_readdir()
5fc1b41 ubifs: Fix xattr_names length in exit paths
cfd4e39 ubifs: Fix assertion in layout_in_gaps()
8b79f32 ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
c7e3bdd ocfs2/dlm: fix race between convert and migration
879149a btrfs: ensure that file descriptor used with subvol ioctls is a dir
444f0f1 libxfs: clean up _calc_dquots_per_chunk
5a8afb1 xfs: fix superblock inprogress check
ee89427 reiserfs: Unlock superblock before calling reiserfs_quota_on_mount()
52495e7 reiserfs: fix "new_insert_key may be used uninitialized ..."
a7ee70f ext4: sanity check the block and cluster size at mount time
7a97321 ext4: allow DAX writeback for hole punch
1326ba8 ext4: reinforce check of i_dtime when clearing high fields of uid and gid
fa8a01a ext4: use __GFP_NOFAIL in ext4_free_blocks()
3a45bbb ext4: avoid modifying checksum fields directly during checksum verification
7d50661 ext4: validate that metadata blocks do not overlap superblock
9c30efd scsi: arcmsr: Send SYNCHRONIZE_CACHE command to firmware
bdf7e17 scsi: scsi_debug: Fix memory leak if LBP enabled and module is unloaded
7a03031 scsi: arcmsr: Buffer overflow in arcmsr_iop_message_xfer()
ba02e93 scsi: Fix use-after-free
f6e64a4 scsi: ibmvfc: Fix I/O hang when port is not mapped
bb3445f scsi: megaraid_sas: fix macro MEGASAS_IS_LOGICAL to avoid regression
0036004 scsi: megaraid_sas: Fix data integrity failure for JBOD (passthrough) devices
0ae4976 mpt2sas: Fix secure erase premature termination
dafa91f scsi: mpt3sas: fix hang on ata passthrough commands
d99fcf7 scsi: mpt3sas: Unblock device after controller reset
3a0c14e scsi: mpt3sas: Fix secure erase premature termination
7ddb258 scsi: zfcp: spin_lock_irqsave() is not nestable
beb0b6c zfcp: trace full payload of all SAN records (req,resp,iels)
569816b zfcp: fix payload trace length for SAN request&response
46737af zfcp: fix D_ID field with actual value on tracing SAN responses
8467dd4 zfcp: restore tracing of handle for port and LUN with HBA records
6916909 zfcp: trace on request for open and close of WKA port
0530772 zfcp: restore: Dont use 0 to indicate invalid LUN in rec trace
909987d zfcp: retain trace level for SCSI and HBA FSF response records
efaebcb zfcp: close window with unblocked rport during rport gone
5f62704 zfcp: fix ELS/GS request&response length for hardware data router
6d35bb9 zfcp: fix fc_host port_type with NPIV
a27178e ALSA: pcm : Call kill_fasync() in stream lock
3d4cfa9 ALSA: ali5451: Fix out-of-bound position reporting
e13285a ALSA: timer: fix NULL pointer dereference on memory allocation failure
3fcea56 ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
cd0365e7 ALSA: timer: fix NULL pointer dereference in read()/ioctl() race
c5bbf9a ALSA: rawmidi: Fix possible deadlock with virmidi registration
64c179f Fix USB CB/CBI storage devices with CONFIG_VMAP_STACK=y
82e6314 usb: chipidea: move the lock initialization to core file
990d13a usb: gadget: u_ether: remove interrupt throttling
dfa4b7a USB: serial: cp210x: fix tiocmget error handling
5c82a63 usb: gadget: function: u_ether: don't starve tx request queue
de57bad usb: misc: legousbtower: Fix NULL pointer deference
98e0190 USB: serial: cp210x: fix hardware flow-control disable
e51960f usb: gadget: fsl_qe_udc: signedness bug in qe_get_frame()
4809107 USB: change bInterval default to 10 ms
096a685 usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
65c2174 USB: serial: mos7840: fix non-atomic allocation in write path
0da1673 USB: serial: mos7720: fix non-atomic allocation in write path
8919643 USB: kobil_sct: fix non-atomic allocation in write path
dd33a40 USB: serial: fix memleak in driver-registration error path
124253f usb: xhci: Fix panic if disconnect
bb9a7c5 USB: fix typo in wMaxPacketSize validation
2226a52 USB: validate wMaxPacketValue entries in endpoint descriptors
1cb7105 usb: dwc3: gadget: increment request->actual once
d112852 coredump: fix unfreezable coredumping task
f2dc0d7 swapfile: fix memory corruption via malformed swapfile
0ffa168 Fix potential infoleak in older kernels
89576ff arc: don't leak bits of kernel stack into coredump
7bb0f7e fix memory leaks in tracing_buffers_splice_read()
138c012 fix fault_in_multipages_...() on architectures with no-op access_ok()
1eeb8d1 ia64: copy_from_user() should zero the destination on access_ok() failure
37b00bc ppc32: fix copy_from_user()
601d291 sparc32: fix copy_from_user()
88e42bd mn10300: copy_from_user() should zero on access_ok() failure...
3c5d8c4 openrisc: fix the fix of copy_from_user()
298c077 openrisc: fix copy_from_user()
fc1e56c parisc: fix copy_from_user()
d01c959 metag: copy_from_user() should zero the destination on access_ok() failure
351a44f alpha: fix copy_from_user()
61e7341 asm-generic: make copy_from_user() zero the destination properly
c946f64 mips: copy_from_user() must zero the destination on access_ok() failure
0ea4b0e hexagon: fix strncpy_from_user() error return
a6c16ec sh: fix copy_from_user()
a0c422b score: fix copy_from_user() and friends
668a740 blackfin: fix copy_from_user()
b5f6c58 cris: buggered copy_from_user/copy_to_user/clear_user
233d4b1 frv: fix clear_user()
44ccf7f asm-generic: make get_user() clear the destination on errors
df37588 ARC: uaccess: get_user to zero out dest in cause of fault
ed98892 s390: get_user() should zero on failure
60f0190 score: fix __get_user/get_user
643d0a2 sh64: failing __get_user() should zero
322dab0 m32r: fix __get_user()
7d84a5d mn10300: failing __get_user() and get_user() should zero
22e232d microblaze: fix copy_from_user()
90f2278 microblaze: fix __get_user()
61f2d84 parisc: Ensure consistent state when switching to kernel stack at syscall entry
2fe6f38 s390/dasd: fix hanging device after clear subchannel
cba31cb avr32: off by one in at32_init_pio()
da189d0 avr32: fix 'undefined reference to `___copy_from_user'
91be3ab avr32: fix copy_from_user()
ac78e19 powerpc/nvram: Fix an incorrect partition merge
5daad2c powerpc/64: Fix incorrect return value from __copy_tofrom_user
6d13a7b powerpc/powernv: Use CPU-endian PEST in pnv_pci_dump_p7ioc_diag_data()
546731a powerpc/vdso64: Use double word compare on pointers
b0a4c16 powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
4787d83 MIPS: ptrace: Fix regs_return_value for kernel context
bc9f83e MIPS: Malta: Fix IOCU disable switch read for MIPS64
83099f3 arm64: debug: avoid resetting stepping state machine when TIF_SINGLESTEP
d65df51 arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
1fd5c7b arm64: Define AT_VECTOR_SIZE_ARCH for ARCH_DLINFO
e5471de arm64: avoid returning from bad_mode
eee1bdb ARM: sa1111: fix pcmcia suspend/resume
5b4918c ARM: sa1100: clear reset status prior to reboot
1774ca8 ARM: 8618/1: decompressor: reset ttbcr fields to use TTBR0 on ARMv7
88654a1 ARM: 8616/1: dt: Respect property size when parsing CPUs
7a6111b iommu/amd: Free domain id when free a domain of struct dma_ops_domain
56eb0df iommu/amd: Update Alias-DTE in update_device_table()
69c373d x86/um: reuse asm-generic/barrier.h
186c5f3 x86/build: Build compressed x86 kernels as PIE
6523fa8 x86/paravirt: Do not trace _paravirt_ident_*() functions
1eae225 x86/mm/pat, /dev/mem: Remove superfluous error message
928a277 x86/apic: Do not init irq remapping if ioapic is disabled
b591901 x86/mm: Disable preemption during CR3 read+write
213060d x86/traps: Ignore high word of regs->cs in early_idt_handler_common
506750b x86/xen: fix upper bound of pmd loop in xen_cleanhighmap()
f014225 xen-pciback: Add name prefix to global 'permissive' variable
1d9d642c xen/pciback: Don't allow MSI-X ops if PCI_COMMAND_MEMORY is not set.
4c2e2fd xen/pciback: For XEN_PCI_OP_disable_msi[|x] only disable if device has MSI(X) enabled.
5701f8a xen/pciback: Do not install an IRQ handler for MSI interrupts.
d2dfdba xen/pciback: Return error on XEN_PCI_OP_enable_msix when device has MSI or MSI-X enabled
871e37b xen/pciback: Return error on XEN_PCI_OP_enable_msi when device has MSI or MSI-X enabled
2801814 xen/pciback: Save the number of MSI-X entries to be copied later.
ffb6bca xen/pciback: Save xen_pci_op commands before processing it
d683706 xen-blkback: only read request operation from shared ring once
67434d3 xen-netback: use RING_COPY_REQUEST() throughout
85fed7d xen-netback: don't use last request to determine minimum Tx credit
0a5b4e4 xen: Add RING_COPY_REQUEST()
0679df0 x86/mm/xen: Suppress hugetlbfs in PV guests
068b35e ppp: defer netns reference release for ppp channel
6e5ae96 PM / devfreq: Fix incorrect type issue.
01c2288 KVM: Disable irq while unregistering user notifier
014db7f KVM: x86: fix missed SRCU usage in kvm_lapic_set_vapic_addr
a3e49e6 KVM: x86: fix wbinvd_dirty_mask use-after-free
010a6cc KVM: MIPS: Make ERET handle ERL before EXL
a0753a8 KVM: nVMX: postpone VMCS changes on MSR_IA32_APICBASE write
4c7055f KVM: MIPS: Drop other CPU ASIDs on guest MMU changes
1d3b3d3 KVM: MIPS: Precalculate MMIO load resume PC
63b0fa1 MIPS: KVM: Fix unused variable build warning
4d57910 crypto: gcm - Fix IV buffer size in crypto_gcm_setkey
0b3918f crypto: skcipher - Fix blkcipher walk OOM crash
6ff69ad crypto: cryptd - initialize child shash_desc on import
ca46046 crypto: algif_skcipher - Load TX SG list after waiting
0ac80b6 crypto: algif_skcipher - Fix race condition in skcipher_check_key
54541dc crypto: algif_hash - Fix race condition in hash_check_key
fb0b50c crypto: af_alg - Forbid bind(2) when nokey child sockets are present
9295497 crypto: algif_skcipher - Remove custom release parent function
023fe7b crypto: algif_hash - Remove custom release parent function
61d0583 crypto: af_alg - Allow af_af_alg_release_parent to be called on nokey path
b5b7b2f crypto: algif_skcipher - Add key check exception for cipher_null
16d4044 crypto: skcipher - Add crypto_skcipher_has_setkey
8552975 crypto: algif_hash - Require setkey before accept(2)
389378f crypto: shash - Fix has_key setting
7040a84 crypto: hash - Add crypto_ahash_has_setkey
4ad8ff6 crypto: algif_skcipher - Add nokey compatibility path
a37d089 crypto: af_alg - Add nokey compatibility path
12514d4 crypto: af_alg - Disallow bind/setkey/... after accept(2)
b886719 crypto: algif_skcipher - Require setkey before accept(2)
c73d76d sched/core: Fix an SMP ordering race in try_to_wake_up() vs. schedule()
6a94ced sched/core: Fix a race between try_to_wake_up() and a woken up task

Signed-off-by: Rk779 <Rahulkrishna585@gmail.com>