fix some more conflicts
In file included from drivers/platform/msm/ipa/ipa_v2/ipa_trace.h:135:0,
                 from drivers/platform/msm/ipa/ipa_v2/ipa.c:41:
include/trace/define_trace.h:83:43: fatal error: ./ipa_trace.h: No such file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                           ^